[package]
name = "bip39miner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
csv = "1.3.1"
ratatui = "0.29.0"
